### ISSUE TITLE
Analizar los diferentes content types que estabamos dejando colgados

### ISSUE THREAD

**Issue by Laouen** [partu18/machine_learning#5]
Gaby: yo ya cambie la funcion que usaba para parsear con mime los mails para que me deje un hash con content_types como key y como value la lista de payloads de ese tipo, sin distinguir por mail. Para que sea mas claro que dá ejecutenlo y miren

**Comment by gdefagot** [comment]
Pareceria tener sentido agregar cada content type como feature (cantidad que tiene).

'multipart/alternative' -> Hay algo raro en algunos mails, que termina guardando la instancia en lugar de texto

application/msword -> adjunto de word?

'application/octet-stream' -> binary

'message/delivery-status' -> idem alternative

'multipart/mixed' -> tiene texto tambien

'multipart/related' -> tiene HTML

**Comment by gdefagot** [comment]
'multipart/alternative' -> Hay algo raro en algunos mails, que termina guardando la instancia en lugar de texto

application/msword -> adjunto de word?

'application/octet-stream' -> binary

'message/delivery-status' -> idem alternative

'multipart/mixed' -> tiene texto tambien

'multipart/related' -> tiene HTML
